CREATE TABLE IF NOT EXISTS t_mcp_tool_call_audit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_type VARCHAR(32) NOT NULL COMMENT 'CONVERSATION / WORKFLOW / UNKNOWN',
    conversation_session_id BIGINT NULL COMMENT '会话 ID',
    conversation_message_id BIGINT NULL COMMENT '助手消息 ID',
    workflow_run_id BIGINT NULL COMMENT '工作流运行 ID',
    workflow_node_key VARCHAR(128) NULL COMMENT '工作流节点 key',
    mcp_server_id BIGINT NOT NULL COMMENT 'MCP Server ID',
    tool_name VARCHAR(128) NOT NULL COMMENT '工具名称',
    argument_keys JSON NULL COMMENT '仅保存参数 key，不保存参数值',
    argument_summary VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '参数摘要',
    success TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否成功',
    elapsed_ms BIGINT NULL COMMENT '耗时毫秒',
    result_summary VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '结果摘要',
    error_summary VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '错误摘要',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_conv_msg (conversation_message_id, deleted, created_at),
    INDEX idx_workflow_run (workflow_run_id, deleted, created_at),
    INDEX idx_server_tool (mcp_server_id, tool_name, deleted, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MCP 工具调用审计';
