DROP TABLE IF EXISTS t_app_job_run_log;
DROP TABLE IF EXISTS t_ops_log_archive;
DROP TABLE IF EXISTS t_rate_limit_quota;
DROP TABLE IF EXISTS t_system_setting;
DROP TABLE IF EXISTS t_llm_call_stat;
DROP TABLE IF EXISTS t_model_default_policy;
DROP TABLE IF EXISTS t_audit_log;
DROP TABLE IF EXISTS t_rag_retrieval_trace;
DROP TABLE IF EXISTS t_knowledge_task;
DROP TABLE IF EXISTS t_knowledge_document;
DROP TABLE IF EXISTS t_knowledge_base;
DROP TABLE IF EXISTS t_conversation_trace;
DROP TABLE IF EXISTS t_conversation_llm_trace;
DROP TABLE IF EXISTS t_conversation_rag_trace;
DROP TABLE IF EXISTS t_mcp_tool_call_audit;
DROP TABLE IF EXISTS t_chat_message;
DROP TABLE IF EXISTS t_chat_session_summary;
DROP TABLE IF EXISTS t_chat_session;
DROP TABLE IF EXISTS t_message_feedback;
DROP TABLE IF EXISTS t_workflow_run;
DROP TABLE IF EXISTS t_workflow;
DROP TABLE IF EXISTS t_agent_api_key;
DROP TABLE IF EXISTS t_agent_app;
DROP TABLE IF EXISTS t_agent_version;
DROP TABLE IF EXISTS t_agent_tool;
DROP TABLE IF EXISTS t_agent;
DROP TABLE IF EXISTS t_mcp_tool;
DROP TABLE IF EXISTS t_mcp_server;
DROP TABLE IF EXISTS t_model_config;
DROP TABLE IF EXISTS t_provider_health;
DROP TABLE IF EXISTS t_provider;
DROP TABLE IF EXISTS t_project_member;
DROP TABLE IF EXISTS t_project;
DROP TABLE IF EXISTS t_workspace;
DROP TABLE IF EXISTS t_user_session;
DROP TABLE IF EXISTS t_user;

CREATE TABLE t_workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_project_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(64) NOT NULL DEFAULT '',
    password_hash VARCHAR(255) NOT NULL DEFAULT '',
    role VARCHAR(20) NOT NULL DEFAULT 'VIEWER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_user_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    base_url VARCHAR(500) NOT NULL DEFAULT '',
    auth_config VARCHAR(2000),
    enabled TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_provider_type_deleted ON t_provider (type, deleted);

CREATE TABLE t_provider_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    last_check_at TIMESTAMP,
    last_success_at TIMESTAMP,
    last_error_at TIMESTAMP,
    last_alert_at TIMESTAMP,
    alert_status VARCHAR(20) NOT NULL DEFAULT 'OK',
    fail_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    total_check_count INT NOT NULL DEFAULT 0,
    latency_ms INT,
    error_message VARCHAR(500) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_provider_health_provider_id ON t_provider_health (provider_id);

CREATE TABLE t_model_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    model_id VARCHAR(100) NOT NULL,
    model_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    context_size INT,
    extra_params VARCHAR(2000),
    enabled TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_model_provider_deleted ON t_model_config (provider_id, deleted);

CREATE TABLE t_model_default_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL DEFAULT 0,
    model_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    provider_type VARCHAR(64) NOT NULL DEFAULT '',
    model_config_id BIGINT NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64),
    actor_user_id BIGINT,
    actor_username VARCHAR(128) NOT NULL DEFAULT '',
    workspace_id BIGINT,
    project_id BIGINT,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BIGINT,
    resource_name VARCHAR(255),
    request_method VARCHAR(16),
    request_path VARCHAR(500),
    client_ip VARCHAR(64),
    user_agent VARCHAR(500),
    success TINYINT NOT NULL DEFAULT 1,
    error_code VARCHAR(64),
    error_message VARCHAR(500),
    before_json CLOB,
    after_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PROJECT',
    share_scope VARCHAR(32) NOT NULL DEFAULT 'PROJECT',
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    embedding_model_config_id BIGINT NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    document_count INT NOT NULL DEFAULT 0,
    chunk_count INT NOT NULL DEFAULT 0,
    retrieval_mode VARCHAR(32) NOT NULL DEFAULT 'VECTOR',
    hybrid_alpha DECIMAL(5, 4) NOT NULL DEFAULT 0.7000,
    top_k INT NOT NULL DEFAULT 5,
    candidate_top_k INT NOT NULL DEFAULT 20,
    score_threshold DECIMAL(6, 5) NOT NULL DEFAULT 0.65000,
    chunk_size INT NOT NULL DEFAULT 512,
    chunk_overlap INT NOT NULL DEFAULT 64,
    max_context_tokens INT NOT NULL DEFAULT 3000,
    rerank_enabled TINYINT NOT NULL DEFAULT 0,
    rerank_model_config_id BIGINT,
    rerank_top_n INT NOT NULL DEFAULT 20,
    metadata_filter_enabled TINYINT NOT NULL DEFAULT 0,
    default_metadata_filter_json CLOB,
    active_index_version BIGINT NOT NULL DEFAULT 1,
    building_index_version BIGINT,
    index_status VARCHAR(32) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL DEFAULT '',
    file_type VARCHAR(32) NOT NULL DEFAULT '',
    file_size BIGINT,
    storage_path VARCHAR(500) NOT NULL DEFAULT '',
    department VARCHAR(128),
    document_type VARCHAR(64),
    tags_json CLOB,
    permission_scope VARCHAR(32) NOT NULL DEFAULT 'PROJECT',
    parse_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    process_stage VARCHAR(32),
    process_progress INT NOT NULL DEFAULT 0,
    progress INT,
    chunk_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    failed_stage VARCHAR(64),
    retryable TINYINT NOT NULL DEFAULT 1,
    cancel_requested TINYINT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    index_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_knowledge_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT,
    document_id BIGINT,
    task_type VARCHAR(32) NOT NULL DEFAULT 'DOCUMENT_PROCESS',
    task_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    process_stage VARCHAR(32),
    progress INT,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_rag_retrieval_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    source_id VARCHAR(128) NOT NULL DEFAULT '',
    agent_id BIGINT,
    query_text CLOB NOT NULL,
    knowledge_base_ids_json CLOB NOT NULL,
    retrieval_mode VARCHAR(32) NOT NULL DEFAULT 'VECTOR',
    top_k INT,
    score_threshold DECIMAL(6, 5),
    rerank_enabled TINYINT NOT NULL DEFAULT 0,
    selected_chunk_ids_json CLOB NOT NULL,
    hit_count INT NOT NULL DEFAULT 0,
    latency_ms BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
    error_message CLOB,
    detail_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    system_prompt CLOB NOT NULL,
    model_config_id BIGINT NOT NULL,
    workflow_id BIGINT,
    knowledge_base_ids VARCHAR(2000),
    temperature DECIMAL(4, 2) NOT NULL DEFAULT 0.70,
    max_turns INT NOT NULL DEFAULT 20,
    max_tokens INT,
    max_context_turns INT,
    memory_enabled TINYINT NOT NULL DEFAULT 0,
    summary_trigger_message_count INT NOT NULL DEFAULT 20,
    summary_max_tokens INT NOT NULL DEFAULT 512,
    summary_model_config_id BIGINT,
    enabled TINYINT NOT NULL DEFAULT 1,
    draft_version_no INT NOT NULL DEFAULT 1,
    published_version_id BIGINT,
    publish_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    max_tool_rounds INT NOT NULL DEFAULT 5,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_agent_enabled_deleted ON t_agent (enabled, deleted);

CREATE TABLE t_workflow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    enabled TINYINT NOT NULL DEFAULT 1,
    start_node_key VARCHAR(100) NOT NULL DEFAULT 'start',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_workflow_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    workflow_version_id BIGINT,
    trace_id VARCHAR(64),
    rerun_from_run_id BIGINT,
    status VARCHAR(20) NOT NULL,
    input CLOB,
    output CLOB,
    error VARCHAR(500),
    current_node_key VARCHAR(100),
    timeout_at TIMESTAMP,
    run_mode VARCHAR(20) NOT NULL DEFAULT 'ASYNC',
    trigger_type VARCHAR(20),
    trigger_id BIGINT,
    publish_id BIGINT,
    source VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    elapsed_ms INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    finished_at TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_agent_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    system_prompt CLOB NOT NULL,
    model_config_id BIGINT NOT NULL,
    workflow_id BIGINT,
    knowledge_base_ids_json VARCHAR(2000),
    tool_ids_json VARCHAR(2000),
    temperature DECIMAL(4, 2),
    max_tokens INT,
    max_context_turns INT,
    memory_enabled TINYINT NOT NULL DEFAULT 0,
    summary_trigger_message_count INT NOT NULL DEFAULT 20,
    summary_max_tokens INT NOT NULL DEFAULT 512,
    summary_model_config_id BIGINT,
    max_tool_rounds INT NOT NULL DEFAULT 5,
    snapshot_json CLOB,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_agent_app (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    published_version_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    web_enabled TINYINT NOT NULL DEFAULT 1,
    api_enabled TINYINT NOT NULL DEFAULT 1,
    endpoint_path VARCHAR(200) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_agent_api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_app_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    key_prefix VARCHAR(32) NOT NULL DEFAULT '',
    key_hash VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_agent_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    tool_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_tool_agent ON t_agent_tool (agent_id);

CREATE TABLE t_mcp_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    endpoint VARCHAR(500) NOT NULL,
    auth_type VARCHAR(20) NOT NULL DEFAULT 'NONE',
    auth_config VARCHAR(2000) NOT NULL DEFAULT '{}',
    enabled TINYINT NOT NULL DEFAULT 1,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PROJECT',
    share_scope VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    secret_id BIGINT,
    connect_timeout_ms INT NOT NULL DEFAULT 3000,
    read_timeout_ms INT NOT NULL DEFAULT 30000,
    retry_times INT NOT NULL DEFAULT 0,
    retry_interval_ms INT NOT NULL DEFAULT 300,
    fallback_strategy VARCHAR(30) NOT NULL DEFAULT 'FAIL_FAST',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_mcp_server_enabled_deleted ON t_mcp_server (enabled, deleted);

CREATE TABLE t_mcp_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id BIGINT NOT NULL,
    tool_type VARCHAR(20) NOT NULL DEFAULT 'MCP',
    openapi_tool_id BIGINT,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    input_schema VARCHAR(4000),
    dangerous TINYINT NOT NULL DEFAULT 0,
    permission_level VARCHAR(20) NOT NULL DEFAULT 'RUN',
    schema_validation_enabled TINYINT NOT NULL DEFAULT 1,
    timeout_ms INT,
    retry_times INT,
    fallback_strategy VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_mcp_tool_server_deleted ON t_mcp_tool (mcp_server_id, deleted);

CREATE TABLE t_mcp_tool_call_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64),
    source_type VARCHAR(32) NOT NULL,
    workspace_id BIGINT,
    project_id BIGINT,
    agent_id BIGINT,
    app_id BIGINT,
    api_key_id BIGINT,
    user_id BIGINT,
    conversation_session_id BIGINT,
    conversation_message_id BIGINT,
    workflow_run_id BIGINT,
    workflow_id BIGINT,
    workflow_node_key VARCHAR(128),
    mcp_server_id BIGINT NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'FAILED',
    retry_count INT NOT NULL DEFAULT 0,
    timeout_ms INT,
    source_id VARCHAR(100),
    argument_keys VARCHAR(4000),
    argument_summary VARCHAR(1000) NOT NULL DEFAULT '',
    success TINYINT NOT NULL DEFAULT 0,
    elapsed_ms BIGINT,
    result_summary VARCHAR(1000) NOT NULL DEFAULT '',
    error_summary VARCHAR(1000) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    app_id BIGINT,
    api_key_id BIGINT,
    title VARCHAR(200) NOT NULL DEFAULT '新对话',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    message_count INT NOT NULL DEFAULT 0,
    last_message_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_session_agent ON t_chat_session (agent_id, deleted);

CREATE TABLE t_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    trace_id VARCHAR(64),
    role VARCHAR(20) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DONE',
    tool_calls VARCHAR(4000),
    tool_call_id VARCHAR(100),
    tokens INT,
    finish_reason VARCHAR(20),
    latency_ms INT,
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    debug_error CLOB,
    partial TINYINT NOT NULL DEFAULT 0,
    total_latency_ms INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_message_session ON t_chat_message (session_id, deleted, created_at);

CREATE TABLE t_chat_session_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    summary CLOB NOT NULL,
    message_count INT NOT NULL DEFAULT 0,
    model_config_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DONE',
    error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_conversation_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    session_id BIGINT NOT NULL,
    user_id BIGINT,
    project_id BIGINT,
    app_id BIGINT,
    api_key_id BIGINT,
    user_message_id BIGINT NOT NULL,
    assistant_message_id BIGINT,
    agent_id BIGINT NOT NULL,
    agent_name VARCHAR(128),
    agent_version_id BIGINT,
    agent_version_no INT,
    agent_system_prompt CLOB,
    max_tool_rounds INT,
    model_config_id BIGINT,
    provider_id BIGINT,
    provider_name VARCHAR(128),
    provider_type VARCHAR(32),
    model_id VARCHAR(128),
    workflow_id BIGINT,
    workflow_run_id BIGINT,
    rag_triggered TINYINT NOT NULL DEFAULT 0,
    mcp_triggered TINYINT NOT NULL DEFAULT 0,
    memory_enabled TINYINT NOT NULL DEFAULT 0,
    summary_used TINYINT NOT NULL DEFAULT 0,
    summary_version INT,
    summary_latency_ms INT,
    summary_error_message VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_token_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_conversation_llm_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    provider_id BIGINT,
    provider_name VARCHAR(128),
    provider_type VARCHAR(32),
    model_config_id BIGINT,
    model_id VARCHAR(128),
    streaming TINYINT NOT NULL DEFAULT 0,
    request_summary OTHER,
    input_tokens INT,
    output_tokens INT,
    first_token_latency_ms INT,
    total_latency_ms INT,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_conversation_rag_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    knowledge_base_id BIGINT NOT NULL,
    knowledge_base_name VARCHAR(128),
    document_id VARCHAR(128),
    document_name VARCHAR(255),
    chunk_id BIGINT,
    chunk_index INT,
    score DECIMAL(10, 6),
    content_preview VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_llm_call_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL DEFAULT '',
    user_id BIGINT,
    project_id BIGINT,
    app_id BIGINT,
    agent_id BIGINT,
    provider_id BIGINT NOT NULL,
    provider_type VARCHAR(64) NOT NULL DEFAULT '',
    model_config_id BIGINT NOT NULL,
    model_id VARCHAR(128) NOT NULL DEFAULT '',
    call_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    success TINYINT NOT NULL DEFAULT 1,
    fallback_used TINYINT NOT NULL DEFAULT 0,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    latency_ms INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NOT NULL DEFAULT '',
    error_message VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_message_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    project_id BIGINT,
    trace_id VARCHAR(64),
    user_id BIGINT NOT NULL DEFAULT 0,
    rating VARCHAR(20) NOT NULL DEFAULT '',
    issue_type VARCHAR(64) NOT NULL DEFAULT '',
    comment VARCHAR(1000) NOT NULL DEFAULT '',
    corrected_answer CLOB,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    review_status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolution_note VARCHAR(1000) NOT NULL DEFAULT '',
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_system_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(128) NOT NULL,
    setting_value CLOB NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_rate_limit_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL DEFAULT 'GLOBAL',
    scope_id BIGINT NOT NULL DEFAULT 0,
    dimension VARCHAR(32) NOT NULL,
    quota_key VARCHAR(128) NOT NULL DEFAULT '*',
    limit_count INT NOT NULL,
    window_sec INT NOT NULL DEFAULT 60,
    fail_open TINYINT NOT NULL DEFAULT 1,
    enabled TINYINT NOT NULL DEFAULT 1,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_app_job_run_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    elapsed_ms BIGINT NOT NULL DEFAULT 0,
    affected_rows INT NOT NULL DEFAULT 0,
    error_summary VARCHAR(1000) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE t_ops_log_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_type VARCHAR(32) NOT NULL,
    source_table VARCHAR(100) NOT NULL,
    source_id BIGINT NOT NULL,
    payload_json CLOB NOT NULL,
    archived_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);
