DROP TABLE IF EXISTS t_provider_health;
DROP TABLE IF EXISTS t_chat_message;
DROP TABLE IF EXISTS t_chat_session;
DROP TABLE IF EXISTS t_agent_tool;
DROP TABLE IF EXISTS t_agent;
DROP TABLE IF EXISTS t_mcp_tool;
DROP TABLE IF EXISTS t_mcp_server;
DROP TABLE IF EXISTS t_model_config;
DROP TABLE IF EXISTS t_provider;

CREATE TABLE t_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    base_url VARCHAR(500) NOT NULL DEFAULT '',
    auth_config VARCHAR(2000),
    enabled TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_provider_type_deleted ON t_provider (type, deleted);

CREATE TABLE t_model_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    model_id VARCHAR(100) NOT NULL,
    model_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    context_size INT,
    extra_params VARCHAR(2000),
    enabled TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_model_provider_deleted ON t_model_config (provider_id, deleted);

CREATE TABLE t_provider_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    last_check_at TIMESTAMP,
    last_success_at TIMESTAMP,
    fail_count INT NOT NULL DEFAULT 0,
    latency_ms INT,
    error_message VARCHAR(500) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_provider_health_provider_id ON t_provider_health (provider_id);

CREATE TABLE t_agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    system_prompt CLOB NOT NULL,
    model_config_id BIGINT NOT NULL,
    workflow_id BIGINT,
    knowledge_base_ids VARCHAR(2000),
    temperature DECIMAL(4, 2) NOT NULL DEFAULT 0.70,
    max_turns INT NOT NULL DEFAULT 20,
    max_tokens INT,
    max_context_turns INT,
    enabled TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_agent_enabled_deleted ON t_agent (enabled, deleted);

CREATE TABLE t_agent_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    tool_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_tool_agent ON t_agent_tool (agent_id);

CREATE TABLE t_mcp_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    endpoint VARCHAR(500) NOT NULL,
    auth_type VARCHAR(20) NOT NULL DEFAULT 'NONE',
    auth_config VARCHAR(2000) NOT NULL DEFAULT '{}',
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_mcp_server_enabled_deleted ON t_mcp_server (enabled, deleted);

CREATE TABLE t_mcp_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    input_schema VARCHAR(4000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_mcp_tool_server_deleted ON t_mcp_tool (mcp_server_id, deleted);

CREATE TABLE IF NOT EXISTS t_mcp_tool_call_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    conversation_session_id BIGINT,
    conversation_message_id BIGINT,
    workflow_run_id BIGINT,
    workflow_node_key VARCHAR(128),
    mcp_server_id BIGINT NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    argument_keys VARCHAR(4000),
    argument_summary VARCHAR(1000) NOT NULL DEFAULT '',
    success TINYINT NOT NULL DEFAULT 0,
    elapsed_ms BIGINT,
    result_summary VARCHAR(1000) NOT NULL DEFAULT '',
    error_summary VARCHAR(1000) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_mcp_audit_conv_msg ON t_mcp_tool_call_audit (conversation_message_id, deleted, created_at);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_workflow_run ON t_mcp_tool_call_audit (workflow_run_id, deleted, created_at);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_server_tool ON t_mcp_tool_call_audit (mcp_server_id, tool_name, deleted, created_at);

CREATE TABLE t_chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    title VARCHAR(200) NOT NULL DEFAULT '新对话',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    message_count INT NOT NULL DEFAULT 0,
    last_message_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_session_agent ON t_chat_session (agent_id, deleted);

CREATE TABLE t_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DONE',
    tool_calls VARCHAR(4000),
    tool_call_id VARCHAR(100),
    tokens INT,
    finish_reason VARCHAR(20),
    latency_ms INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_message_session ON t_chat_message (session_id, deleted, created_at);
